apiVersion : apps/v1
kind: Deployment
metadata:
  name: fantastic-show
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fantastic-show
  template:
    metadata:
      labels:
        app: fantastic-show
    spec:
      containers:
        - name: fantastic-show
          image: docker.io/tazvoit/fantastic-show:138
          ports:
          - containerPort: 8080
