apiVersion: v1
kind: Service
metadata:
  name: fantastic-show
spec:
  selector:
    app: fantastic-show
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: fantastic-show
spec:
  to:
    kind: Service
    name: fantastic-show
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
